// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPM2U_m8j6zXutazS99oMqnZREwbIn0cI',
    appId: '1:138195559813:web:1524f31b8b881bc5c950ec',
    messagingSenderId: '138195559813',
    projectId: 'journalia-b5e15',
    authDomain: 'journalia-b5e15.firebaseapp.com',
    storageBucket: 'journalia-b5e15.appspot.com',
    measurementId: 'G-KDQCN2X44T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyT8Tz5DjgxAsPYPYv7ysB8tjRr0c43-8',
    appId: '1:138195559813:android:f4aaff408c6934bdc950ec',
    messagingSenderId: '138195559813',
    projectId: 'journalia-b5e15',
    storageBucket: 'journalia-b5e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EZEDp7QLQuwnBh3XTmq12mT-qeDlLkM',
    appId: '1:138195559813:ios:e5108e819d98953ec950ec',
    messagingSenderId: '138195559813',
    projectId: 'journalia-b5e15',
    storageBucket: 'journalia-b5e15.appspot.com',
    iosBundleId: 'com.example.journalia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0EZEDp7QLQuwnBh3XTmq12mT-qeDlLkM',
    appId: '1:138195559813:ios:e5108e819d98953ec950ec',
    messagingSenderId: '138195559813',
    projectId: 'journalia-b5e15',
    storageBucket: 'journalia-b5e15.appspot.com',
    iosBundleId: 'com.example.journalia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPM2U_m8j6zXutazS99oMqnZREwbIn0cI',
    appId: '1:138195559813:web:d12aa05909995b0cc950ec',
    messagingSenderId: '138195559813',
    projectId: 'journalia-b5e15',
    authDomain: 'journalia-b5e15.firebaseapp.com',
    storageBucket: 'journalia-b5e15.appspot.com',
    measurementId: 'G-Q32K81HT71',
  );
}
